# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05a82b6d788cc51865a83772a4fef3e64d6738d2d1d795295d630bd49160a696679307c33efe362b2d70038659695ee9af8f4eccf4660c9ae707261a8531bf03

test:
  secret_key_base: a7e99db3f494bbd38fa20494b2ab1f5d990bb509dbca830a0deca4a4f7797cbd6cf658e8df7a5036890329c3a8a4c4019c4bb77318466356fbac14a05ac3ba34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
